SUMMARY_DB_PATH = "compact_db"
LABEL_FILTER_DB_PATH = "label_filter_db"

USER_START = 1
USER_END = 1000

# MODEL_PATH = "pretrain/lstm_encoder/LSTM encoder attention res sqrt decay_29999.pth"
# OUT_NAME = "LSTM-encoder"
MODEL_PATH = "pretrain/lstm_encoder/FSRS baseline_199999.pth"
OUT_NAME = "LogisticRegression31"

DEVICE = "cuda"

PROCESSES = 1

# Clear the CUDA cache if the reserved memory is over a certain amount
THRESHOLD_RESERVED_GB = 7.0