SUMMARY_DB_PATH = "compact_db"
LABEL_FILTER_DB_PATH = "label_filter_db"

SEED = 111

TRAIN_USER_START = 5001
TRAIN_USER_END = 10000

# Include some users from the train set to gauge for overfitting
VALIDATE_OVERFIT_USER_START = 5001
VALIDATE_OVERFIT_USER_END = 5100

VALIDATE_USER_START = 1
VALIDATE_USER_END = 100

DEVICE = "cuda"
DTYPE = "float"

# If we use a warmup, set the lr to start at for the warmup. Useful for continuing a run that was in the middle of a warmup
WARMUP_START_LR = 0
PEAK_LR = 2e-3

# Available modes are "WS" and "D" for the corresponding phases of the WSD learning rate scheduler.
TRAIN_MODE = "WS"
START_STEP = 0
WARMUP_STEPS = 20000
TOTAL_STEPS = 1000000000
VALIDATE_STEPS = 2500

LOAD_MODEL = false
LOAD_MODEL_FOLDER = "pretrain/lstm_encoder"
LOAD_MODEL_NAME = "lstm_encoder_big_39999"
SAVE_MODEL_FOLDER = "pretrain/lstm_encoder"
SAVE_MODEL_PREFIX = "lstm_encoder_big"

USE_WANDB = true
WANDB_PROJECT_NAME = "LSTM encoder"
WANDB_RUN_NAME = "l to 0"           # Human-readable name shown in UI and the ID
WANDB_RESUME_MODE = "never"   # "never" | "allow" | "must" | "auto"

# Skip batches of a certain length of longer
SKIP_LENGTH = 600_000
# Clear the CUDA cache if the reserved memory is over a certain amount
THRESHOLD_RESERVED_GB = 7.0