SUMMARY_DB_PATH = "compact_db"
LABEL_FILTER_DB_PATH = "label_filter_db"

SEED = 111

TRAIN_USER_START = 5001
TRAIN_USER_END = 10000

# Include some users from the train set to gauge for overfitting
VALIDATE_OVERFIT_USER_START = 5001
VALIDATE_OVERFIT_USER_END = 5100

VALIDATE_USER_START = 1
VALIDATE_USER_END = 100

DEVICE = "cuda"
DTYPE = "float"

# If we use a warmup, set the lr to start at for the warmup. Useful for continuing a run that was in the middle of a warmup
WARMUP_START_LR = 0
PEAK_LR = 3e-3

# for FSRS
USE_MAX_SEQ_LEN = true
MERGE_DECODE_BATCHES = false

TRAIN_MODE = "WSD" # options are "WSD", "D"
START_STEP = 0
START_SCHEDULER_AT_START_STEP = true
WARMUP_STEPS = 6000
TOTAL_STEPS = 100000
VALIDATE_STEPS = 5000

LOAD_MODEL = true
LOAD_MODEL_FOLDER = "pretrain/lstm_encoder"
# LOAD_MODEL_NAME = "LSTM encoder attention res cosine decay_29999"
LOAD_MODEL_NAME = "dev_0"
SAVE_MODEL_FOLDER = "pretrain/lstm_encoder"
SAVE_MODEL_PREFIX = "dev"

USE_WANDB = true
WANDB_PROJECT_NAME = "LSTM encoder"
WANDB_RUN_NAME = "ff fsrs curve 3"  # Human-readable name shown in UI and the ID
WANDB_RESUME_MODE = "never"   # "never" | "allow" | "must" | "auto"

# Skip batches of a certain length of longer
SKIP_LENGTH = 700_000
# Clear the CUDA cache if the reserved memory is over a certain amount
THRESHOLD_RESERVED_GB = 7.6